<?php
include_once 'scripts/grabber.php';

if (authenticated()) {
	userLinks();
}
else {
	header( 'Location: index.php' );
}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="x-ua-compatible" content="IE=9">
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<?php printCssSheets(); ?>
		<title>Dandelion Web Log</title>
	</head>
	<body>
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
        <h2>Administration</h2>
		
    	<form name="admin_form" method="post" action="scripts/admin_actions.php">
			<input type="button" class="dButton adminButton" value="Manage Users" onClick="window.location='editusers.phtml'"><br>
			<input type="button" class="dButton adminButton" value="Manage Categories" onClick="window.location='categories.phtml'"><br>
			<input type="button" class="dButton adminButton" onClick="adminAction.editSlogan('<?php echo addslashes($_SESSION['app_settings']['slogan']); ?>');" value="Edit Site Slogan">
			<br><br><hr width="350">
			<h3>Database Administration</h3>
			<input type="button" class="dButton adminButton" value="Export Database to File" onClick="adminAction.backupDB();" title="Creates a single file backup of the Dandelion database tables.&#013;If you have a lot of log entries, the file will be large."><br>
    	</form>

        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
        
        <script src="js/lQuery.js"></script>
        <script src="js/admin.js"></script>
	</body>
</html>
