<?php
include_once 'scripts/grabber.php';

if (!authenticated()) {
	header( 'Location: index.php' );
}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="x-ua-compatible" content="IE=9">
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<?php echo loadCssSheets(); ?>
		<title>Dandelion Web Log</title>
	</head>
	<body onLoad="CategoryManage.grabNextLevel('0:0');">
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
        <h3>Category Management</h3>
        
        <div id="message"></div>

        <form method="post">
        	<div name="categorySelects" id="categorySelects"></div><br><br>
        	
        	<?php
        	if ($_SESSION['rights']['addcat']) {
				echo '<input type="button" class="dButton" onClick="CategoryManage.createNew();" value="Add Category">';
			}
			
			if ($_SESSION['rights']['editcat']) {
				echo '<input type="button" class="dButton" onClick="CategoryManage.editCat();" value="Edit Category">';
			}
			
			if ($_SESSION['rights']['deletecat']) {
				echo '<input type="button" class="dButton" onClick="CategoryManage.deleteCat();" value="Delete Category">';
			}
        	?>
        </form>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
    
    <?php echo loadJS("jquery", "catmanage");?>
</html>
