<!DOCTYPE html>

<?php
include_once 'scripts/dbconnect.php';

// Authenticate user, if fail go to login page
if (checkLogIn()) {
	if ($_SESSION['userInfo']['role'] === "admin") {
		$admin_link = '<a href="admin.phtml">Administration</a>';
	}
	else {
		$admin_link = '';
	}

	if ($_SESSION['userInfo']['role'] !== "guest") {
		$settings_link = '<a href="settings.phtml">Settings</a>';
	}
	else {
		$settings_link = '';
	}
	
	$theme = isset($_SESSION['userInfo']['theme']) ? $_SESSION['userInfo']['theme'] : 'default';
}
else {
	header( 'Location: index.php' );
}
?>

<html>
	<head>
		<meta charset="utf-8" />
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/main.css" />
		<title>Dandelion Web Log</title>
	</head>
	<body> <!--onLoad="showCats(0, 0);">-->
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
        <h3>Category Management</h3>
        
        <div id="message"></div>

        <form>
        	<div id="workArea">
        		<?php include_once 'scripts/categories.php'; ?>
        	</div>
        	<input type="button" onClick="deleteMe();" value="Delete" />
        </form>
        
        <div id="tester"></div>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
    
    <script type="text/javascript" src="js/catManage.js"></script>
    <script type="text/javascript" src="js/mainLib.js"></script>
</html>
