<!DOCTYPE html>

<?php
include_once 'scripts/dbconnect.php';

//Authenticate user, if fail go to login page
if (checkLogIn()) {
	if ($_SESSION['userInfo']['role'] === "admin") {
		$admin_link = '<a href="admin.phtml">Administration</a>';
	}
	else {
		$admin_link = '';
	}
	
	if ($_SESSION['userInfo']['role'] !== "guest") {
		$settings_link = '<a href="settings.phtml">Settings</a>';
	}
	else {
		$settings_link = '';
	}
}
else {
	header( 'Location: index.php' );
}

$showList = true;
?>

<html>
	<head>
		<meta charset="utf-8" />
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
		<link rel="stylesheet" type="text/css" href="jquery/css/smoothness/jquery-ui.min.css" />
		<title>Dandelion Web Log</title>
	</head>
	<body>
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
        
		<?php include 'scripts/editusersaction.php'; ?>
		
        <?php if ($showList) {?>
            <form method="post">
                Action: 
                <select name="user_action2">
                    <option value="none">Select:</option>
                    <option value="cxeesto">Change &#264;eesto</option>
                    <option value="delete">Delete</option>
                    <option value="edit">Edit</option>
                    <option value="reset">Reset Password</option>
                    <option value="add">Add User</option>
                </select>
                
                <input type="submit" name="sub_type" value="Go" />
                
                <br /><br />
                
                <table id="main">
                    <tr>
                        <th>&nbsp;</th>
                        <!--<th>User ID</th>-->
                        <th>Real Name</th>
                        <th>Username</th>
                        <th>Settings ID</th>
                        <th>Role</th>
                        <th>Date Created</th>
                        <th>First Login</th>
                    </tr>
                    
                    <?php
                        $stmt = 'SELECT * FROM users';
                        $allUsers = $conn->queryDB($stmt, NULL);
                        foreach ($allUsers as $row) {
                            echo '<tr>';
                            echo '<td><input type="radio" name="the_choosen_one" value="' . $row['userid'] . '" /></td>';
                            //echo '<td>' . $row['userid'] . '</td>';
                            echo '<td>' . $row['realname'] . '</td>';
                            echo '<td>' . $row['username'] . '</td>';
                            echo '<td>' . $row['settings_id'] . '</td>';
                            echo '<td>' . $row['role'] . '</td>';
                            echo '<td>' . $row['datecreated'] . '</td>';
                            echo '<td>' . $row['firsttime'] . '</td>';
                            echo '</tr>';
                        }
                    ?>
                </table>
                <br />
                
                Action: 
                <select name="user_action">
                    <option value="none">Select:</option>
                    <option value="cxeesto">Change &#264;eesto</option>
                    <option value="delete">Delete</option>
                    <option value="edit">Edit</option>
                    <option value="reset">Reset Password</option>
                    <option value="add">Add User</option>
                </select>
                
                <input type="submit" name="sub_type" value="Go" />
            </form>
        <?php } ?>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
</html>
