<?php
/**
 * Full window for Cxeesto
 *
 * This file is a part of Dandelion
 *
 * @author Lee Keitel
 * @date March 2014
 *
 * @license GNU GPL v3 (see full license in root/LICENSE.md)
 ***/

include_once 'scripts/grabber.php';

if (authenticated()) {
	$theme = getTheme();
}
else {
	header( 'Location: index.php' );
}
?>
<html>
    <head>
        <meta charset="utf-8" />
		<meta http-equiv="x-ua-compatible" content="IE=9">
        <title>Dandelion Presence</title>
		<link rel="stylesheet" type="text/css" href="styles/presence.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/cheesto.css" />
        <link rel="stylesheet" type="text/css" href="styles/presencewin.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/presenceWin.css" />
    </head>
    
    <body onLoad="presence.startR();">
        <?php $windowed = 1; ?>
        <div id="mainWindow">
	        <h3><a href="#" onClick="window.close();" id="showHide">[ x ]</a> &#264;eesto:</h3>
	        <form method="post">
	            <select id="cstatus">
	                <option>Set Status:</option>
	                <option>Available</option>
	                <option>Away From Desk</option>
	                <option>At Lunch</option>
	                <option>Out for Day</option>
	                <option>Out</option>
	                <option>Appointment</option>
	                <option>Do Not Disturb</option>
	                <option>Meeting</option>
	                <option>Out Sick</option>
	                <option>Vacation</option>
	            </select>
	            <input type="button" value="Set" class="linklike set" onClick="presence.setStatus(1);" />
	        </form>
	        <div id="pt">
	            <?php include 'scripts/presence.php'; ?>
	        </div>
        </div>
        
		<script src="js/mainLib.js"></script>
        <script src="js/presence.js"></script>
    </body>
</html>