<!DOCTYPE html>

<?php
/*
 * Lee Keitel
 * January 28, 2014
 *
 * This page allows users to change their password
 * and change the number of logs show on the home page.
*/

include 'scripts/dbconnect.php';

if (checkLogIn()) {
	if ($_SESSION['userInfo']['role'] == "guest") {
		header( 'Location: viewlog.phtml' );
	}
	else {
		$settings_link = '<a href="settings.phtml">Settings</a>';
	}
	
	if ($_SESSION['userInfo']['role'] === "admin") {
		$admin_link = '<a href="admin.phtml">Administration</a>';
	}
	else {
		$admin_link = '';
	}
	
	$theme = getTheme();
}
else {
	header( 'Location: index.php' );
}
?>

<html>
	<head>
		<meta charset="utf-8" />
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/main.css" />
		<title>Dandelion Web Log</title>
	</head>
	<body>
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
		<h2>User Settings</h2>
		
		<?php require_once 'scripts/saveSettings.php';?>

        <form method="post">
            <input type="submit" name="set_action" class="dButton adminButton" value="Reset Password" />
            <br /><br /><hr width="350" /><br />
            
            How many logs do you want to see on the main page:<br />
            <input type="text" name="show_limit" size="3" value="<?php echo $limit; ?>" />
            <input type="submit" name="set_action" class="dButton" value="Save Limit" />
        </form>
        
        <br /><hr width="350" /><br />
        
        <form method="post">
        	Current theme:
        	
        	<?php
        		$handle = opendir('themes');
        		
	        	echo '<select name="userTheme">';
	        		while (false !== ($themeName = readdir($handle))) {
						if ($themeName != '.' && $themeName != '..' && is_dir(THEME_DIR.'/'.$themeName)) {
							if ($themeName == $theme) {
								echo '<option value="'.$themeName.'" selected>'.$themeName.'</option>';
							}
							else {
								echo '<option value="'.$themeName.'">'.$themeName.'</option>';
							}
						}
					}
	        	echo '</select>';
        	?>
            <input type="submit" name="set_action" class="dButton" value="Save Theme" />
        </form>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
</html>
