<!DOCTYPE html>

<?php
/**
 * This page is the heart of the whole application.
 * This page show the weblog and allows a user to search,
 * filter, add, or edit a log. This page also houses the
 * presence application Cxeesto.
 *
 * This file is a part of Dandelion
 *
 * @author Lee Keitel
 * @date January 27, 2014
 *
 * @license GNU GPL v3 (see full license in root/LICENSE.md)
 ***/

include_once 'scripts/grabber.php';

//Authenticate user, if fail go to login page
if (authenticated()) {	
	userLinks();
	
	if ($_SESSION['userInfo']['role'] !== "guest") {
		$add_link = '<input type="button" class="dButton" onClick="addFun.showaddinputs();" value="Add New Log Entry" />';
	}
	else {
		$add_link = '';
	}
	
	$theme = getTheme();
}
else {
	header( 'Location: index.php' );
}

/*
 * Notes:
 * Cxeesto is first called under mainScripts.js -> refreshLog
*/
?>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="IE=9">
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/main.css" />
		<link rel="stylesheet" type="text/css" href="styles/presence.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/cheesto.css" />
		<link rel="stylesheet" type="text/css" href="jquery/css/smoothness/jquery-ui-1.10.4.custom.min.css" />
		<title>Dandelion Web Log</title>
	</head>
    
	<body onLoad="refreshFun.startrefresh();">
        <div id="presence">
	        <h3><a href="#" onClick="presence.showHideP();"><span id="showHide">[ - ]</span></a> &#264;eesto:</h3>
        	<div id="mainPresence">
	            <form method="post">
	                <select id="cstatus">
	                    <option>Set Status:</option>
	                    <option>Available</option>
	                    <option>Away From Desk</option>
	                    <option>At Lunch</option>
	                    <option>Out for Day</option>
	                    <option>Out</option>
	                    <option>Appointment</option>
	                    <option>Do Not Disturb</option>
	                    <option>Meeting</option>
	                    <option>Out Sick</option>
	                    <option>Vacation</option>
	                </select>
	                <input type="button" value="Set" class="linklike set" onClick="presence.setStatus(0);" />
	            </form>
	            <div id="pt"></div>
            </div>
        </div>
    
        <div id="divMain">
            <header>
                <?php include 'scripts/header.php'; ?>
            </header>

            <div id="controlPanel">
                <form id="category" method="post">
                    <input type="text" id="searchterm" size="40" value="Keyword" onClick="miscFun.clearval(this);" onKeyPress="return searchFun.check(event);" /><input type="text" id="datesearch" size="10" value="Date" onClick="miscFun.clearval(this);" />
                    <input type="button" value="Search Log" class="dButton" onClick="searchFun.searchlog();" /><br />
                    
                    <span class="white">Filter: </span>
                    <div id="categorySelects"></div>
                    
                    <input type="button" value="Filter" class="dButton" onClick="searchFun.filter('');" />
                    | <?php echo $add_link; ?>
                </form>
                
                <div id="add_edit"></div>
            </div>
            
            <div id="refreshed"></div>
            
            <footer>
                <?php include_once 'scripts/footer.php'; ?>
            </footer>
        </div>
        
        <script src="jquery/js/jquery-2.1.0.min.js"></script>
        <script src="jquery/js/jquery-ui-1.10.4.custom.min.js"></script>
        <script src="js/lQuery.js"></script>
        <script src="js/catManage.js"></script>
        <script src="js/mainScripts.js"></script>
        <script src="js/presence.js"></script>
	</body>
</html>
