<!DOCTYPE html>

<?php
/**
 * This page is used to show users new features in Dandelion.
 * It can also be used to force users to see announcements,
 * warnings, or other needed items. The page contents are free
 * to change as needed.
 *
 * This file is a part of Dandelion
 *
 * @author Lee Keitel
 * @date January 27, 2014
 *
 * @license GNU GPL v3 (see full license in root/LICENSE.md)
 ***/

include_once 'scripts/grabber.php';

if (authenticated()) {
	userLinks();
    
    if ($_SESSION['userInfo']['firsttime'] == 3) {        
        // Connect to DB
        $conn = new dbManage();

        // Update record and change firsttime
        $stmt = 'UPDATE `users` SET `firsttime` = 0 WHERE `userid` = :myID';
        $params = array(
            'myID' => $_SESSION['userInfo']['userid']
        );
        $conn->queryDB($stmt, $params);
        $_SESSION['userInfo']['firsttime'] = 0;
    }
	
	$theme = getTheme();
}
else {
	header( 'Location: index.php' );
}
?>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="x-ua-compatible" content="IE=9">
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
		<link rel="stylesheet" type="text/css" href="themes/<?php echo $theme;?>/main.css" />
        <link rel="stylesheet" type="text/css" href="styles/tutorial.css" />
		<title>Dandelion Web Log - What's New</title>
	</head>
	<body>
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
		<h2 class="t_cen">New Features</h2>
        
        <p class="le">New features have been added to Dandelion! Check them out below:</p>
		
		<p class="le">
			<ul>
				<li>The main log view now has pagination.</li>
			</ul>
		</p>
        
        <p class="le">In the works:</p>
		
		<p class="le">
			<ul>
				<li>Better visuals.</li>
                <li>LDAP Integration</li>
			</ul>
		</p>

        <p><a href="viewlog.phtml">Continue to Dandelion --></a></p>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
</html>
