<!DOCTYPE html>

<?php
/*
 * Lee Keitel
 * February 4, 2014
 *
 * This page is used to show users new features in Dandelion.
 * It can also be used to force users to see announcements,
 * warnings, or other needed items. The page contents are free
 * to change as needed.
*/

include_once 'scripts/dbconnect.php';

if (checkLogIn()) {

	if ($_SESSION['userInfo']['role'] === "admin") {
		$admin_link = '| <a href="admin.phtml">Administration</a>';
	}
	else {
		$admin_link = '';
	}
	
	if ($_SESSION['userInfo']['role'] !== "guest") {
		$settings_link = '| <a href="settings.phtml">Settings</a>';
	}
	else {
		$settings_link = '';
	}
    
    if ($_SESSION['userInfo']['firsttime'] == 3) {        
        // Connect to DB
        $conn = new dbManage();

        // Update record and change firsttime
        $stmt = 'UPDATE `users` SET `firsttime` = 0 WHERE `userid` = :myID';
        $params = array(
            'myID' => $_SESSION['userInfo']['userid']
        );
        $conn->queryDB($stmt, $params);
        $_SESSION['userInfo']['firsttime'] = 0;
    }
}
else {
	header( 'Location: index.php' );
}
?>
<html>
	<head>
		<meta charset="utf-8" />
        <link rel="icon" type="image/ico" href="images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="styles/main.css" />
        <link rel="stylesheet" type="text/css" href="styles/tutorial.css" />
		<title>Dandelion Web Log - What's New</title>
	</head>
	<body>
        <header>
            <?php include 'scripts/header.php'; ?>
        </header>
		
		<h2 class="t_cen">New Features</h2>
        
        <p class="le">New features have been added to Dandelion! Check them out below:</p>
		
		<p class="le">
			<ul>
				<li>Form Validation has been lightened to allow for more characters to be used</li>
                <li><b>Presence has been added to Dandelion! Now you can tell everyone where you are right from Dandelion. Set your status by using the Presence box in the upper left corner. This box is only visible on the <u>main View Log page</u>.</b></li>
                
			</ul>
		</p>
        
        <p class="le">In the works:</p>
		
		<p class="le">
			<ul>
				<li>Better visuals.</li>
                <li>More/faster functionality through jQuery</li>
                <li>Ease of use.</li>
			</ul>
		</p>
        
        <p>If you have any feature suggestions or need to report a bug, email Lee Keitel at <a href="mailto:lfkeitel@usi.edu">lfkeitel@usi.edu</a></p>
        
        <p><a href="viewlog.phtml">Continue to Dandelion --></a></p>
        
        <footer>
            <?php include_once 'scripts/footer.php'; ?>
        </footer>
	</body>
</html>
